In [2]:
from sagemaker import Session
from sagemaker import get_execution_role
import pandas as pd
import boto3
session = Session()
bucket = session.default_bucket()
prefix = "examples/autopilot-targetincome"
role = get_execution_role()
s3_client = boto3.client("s3")

In [5]:
!wget -O data/adult.data https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data 
!wget -O data/adult.test https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test

--2022-02-27 02:12:36--  https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3974305 (3.8M) [application/x-httpd-php]
Saving to: ‘data/adult.data’

data/adult.data     100%[===================>]   3.79M  7.70MB/s    in 0.5s

2022-02-27 02:12:36 (7.70 MB/s) - ‘data/adult.data’ saved [3974305/3974305]

--2022-02-27 02:12:37--  https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2003153 (1.9M) [application/x-httpd-php]
Saving to: ‘data/adult.test’

data/adult.test     100%[===================>]   1.91M  4.45MB/s    in 0.4s

2022-02-27 02:12:37 (4.45 MB/s) - ‘data/adult.test’ saved [2003153/2003153]

In [6]:
adult_columns = [
"Age",
"Workclass",
"fnlwgt",
"Education",
"Education-Num",
"Marital Status",
"Occupation",
"Relationship",
"Ethnic group",
"Sex",
"Capital Gain",
"Capital Loss",
"Hours per week",
"Country",
"Target",
]

df_train = pd.read_csv("data/adult.data", 
                      names=adult_columns,
                      sep=r"\s*,\s*", 
                      engine="python", 
                      na_values="?")
df_test = pd.read_csv("data/adult.test", 
                      names=adult_columns, 
                      sep=r"\s*,\s*", 
                      engine="python", 
                      na_values="?", 
                      skiprows=1, 
                      header=None)
dataset = pd.concat([df_train,df_test])
dataset.head() # show the first 5 rows

,Age,Workclass,fnlwgt,Education,Education-Num,Marital Status,Occupation,Relationship,Ethnic group,Sex,Capital Gain,Capital Loss,Hours per week,Country,Target
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [7]:
dataset.shape

(48842, 15)

In [8]:
from sagemaker.s3 import S3Uploader
dataset.to_csv("data/adult.data.csv", index=False, header=True)
data_uri = S3Uploader.upload("data/adult.data.csv", "s3://{}/{}/input".format(bucket, prefix))